"""
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

Solved: O(n)
"""

from python.utils import fast_fib
from itertools import count, accumulate


def answer(limit=4e6):
    return next(s for s in accumulate(map(fast_fib, count(step=3))) if s > limit)


if __name__ == '__main__':
    print("Answer is:", answer())
