"""
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

from python.utils import fast_fib
from itertools import count, accumulate


def answer(limit=4e6):
    return next((s for s in accumulate(count(step=3), lambda a, b: a + fast_fib(b), initial=0) if s > limit), None)


if __name__ == '__main__':
    print("Answer is:", answer())
