#=
answer012:
- Julia version: 1.4.2
- Author: Zac
- Date: 2020-09-10

Problem 12:
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

Solved: O(n^2)
=#


function answer(n=1000000, limit=500)
    d = zeros(n)
    for i in 2:n
        for j in i:i:n
            d[j] += 1
        end
        if (i % 2 == 0 ? d[i - 1] * d[div(i, 2)] : d[div(i - 1, 2)] * d[i]) > limit
            return div(i * (i - 1), 2)
        end
    end
end


# Output
println("Answer is: ", answer())
