#=
answer002:
- Julia version: 1.4.2
- Author: Zac
- Date: 2020-07-03

Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
=#
include("utils.jl")


function answer()
    n = 4e6
    s = 0
    for i in Iterators.countfrom(0, 3)
        s += Utils.nthFib(i)
        s >= n && return s
    end
    return nothing
end


# Output
println("Answer is: ", answer())
