#=
answer044:
- Julia version: 1.4.2
- Author: Zac
- Date: 2020-07-11

Problem 44:

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

=#


function answer()
    i = 1001
    s = div(3 * i * i - i, 2)
    ps = Set()
    result = 0
    while !any(s - j in ps && (result = s - 2 * j) in ps for j in ps)
        union!(ps, s)
        i += 1
        s = div(3 * i * i - i, 2)
    end
    return result
end


# Output
println("Answer is: ", answer())

