"""
Question 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

from utils import fast_fib


def answer():
    fib_sum = 0
    n = 0
    limit = 4e6

    # Every third Fibonacci value is even.
    while (fib_n := fast_fib(n := n + 3)) < limit:
        fib_sum += fib_n
    return fib_sum


if __name__ == '__main__':
    print("Answer is:", answer())
